const express = require('express');
const router = express.Router();
const path = require('path');
const fs = require('fs');
const multer = require('multer');
const { Op } = require('sequelize');
const { SupportRequest, SupportRequestUpdate, SupportRequestAttachment, User, sequelize } = require('../models-sql');
const auth = require('../middleware/auth');

const PRIORITY_VALUES = ['low', 'medium', 'high'];
const SUPPORT_UPLOAD_DIR = path.join(__dirname, '../uploads/support');
const ALLOWED_MIME_TYPES = new Set([
  'application/pdf',
  'image/png',
  'image/jpeg',
  'image/jpg',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'text/plain'
]);

function ensureDirectory(targetPath) {
  if (!fs.existsSync(targetPath)) {
    fs.mkdirSync(targetPath, { recursive: true });
  }
}

ensureDirectory(SUPPORT_UPLOAD_DIR);

const supportStorage = multer.diskStorage({
  destination(req, file, cb) {
    ensureDirectory(SUPPORT_UPLOAD_DIR);
    cb(null, SUPPORT_UPLOAD_DIR);
  },
  filename(req, file, cb) {
    const timestamp = Date.now();
    const random = Math.round(Math.random() * 1e9);
    const ext = path.extname(file.originalname) || '';
    cb(null, `support-${timestamp}-${random}${ext}`);
  }
});

function supportFileFilter(req, file, cb) {
  if (ALLOWED_MIME_TYPES.has(file.mimetype)) {
    cb(null, true);
    return;
  }
  cb(new Error('Unsupported attachment type. Allowed formats: pdf, images, word, excel, txt.'));
}

const supportUploadMiddleware = multer({
  storage: supportStorage,
  limits: {
    fileSize: 8 * 1024 * 1024,
    files: 5
  },
  fileFilter: supportFileFilter
}).array('attachments', 5);

/* ── Standard eager-load includes ── */
const standardIncludes = [
  { model: User, as: 'creator', attributes: ['id', 'name', 'email', 'role'] },
  { model: User, as: 'assignee', attributes: ['id', 'name', 'email', 'role'] },
  { model: SupportRequestUpdate, as: 'updates', include: [{ model: User, as: 'actor', attributes: ['id', 'name', 'email', 'role'] }] },
  { model: SupportRequestAttachment, as: 'attachments' }
];

/** Reload a SupportRequest with all associations */
async function reloadWithIncludes(id) {
  return SupportRequest.findByPk(id, { include: standardIncludes });
}

async function resolveDefaultAdmin() {
  return User.findOne({
    where: { role: { [Op.in]: ['Super Admin', 'Admin'] }, activeStatus: 'active' },
    order: [['role', 'ASC']],
    attributes: ['id', 'name', 'email', 'role']
  });
}

function cleanupUploadedFiles(files) {
  if (!Array.isArray(files)) {
    return;
  }
  files.forEach(file => {
    if (file?.path) {
      fs.unlink(file.path, () => {});
    }
  });
}

function uploadAttachments(req, res, next) {
  supportUploadMiddleware(req, res, err => {
    if (err) {
      cleanupUploadedFiles(req.files);
      return res.status(400).json({ msg: err.message || 'Unable to process attachments.' });
    }
    return next();
  });
}

const { requireRole } = require('../middleware/auth');

/* ── POST / — create support request ── */
router.post('/', auth, uploadAttachments, async (req, res) => {
  const t = await sequelize.transaction();
  try {
    const category = (req.body.category || '').toString().trim();
    const subject = (req.body.subject || '').toString().trim();
    const message = (req.body.message || '').toString().trim();
    const requestedPriority = (req.body.priority || 'medium').toString().trim().toLowerCase();
    if (!category || !message) {
      await t.rollback();
      return res.status(400).json({ msg: 'Category and message are required.' });
    }
    const priority = PRIORITY_VALUES.includes(requestedPriority) ? requestedPriority : 'medium';
    const user = await User.findByPk(req.user.userId, { attributes: ['id', 'name', 'email', 'role'] });
    if (!user) {
      await t.rollback();
      return res.status(404).json({ msg: 'User not found' });
    }

    const defaultAdmin = await resolveDefaultAdmin();

    // ticketNumber is auto-generated by the beforeValidate hook
    const supportRequest = await SupportRequest.create({
      createdBy: user.id,
      requesterName: user.name,
      requesterEmail: user.email,
      requesterRole: user.role,
      category,
      priority,
      subject: subject || '',
      message,
      assignedTo: defaultAdmin?.id || null
    }, { transaction: t });

    // Create initial "Ticket created" update
    await SupportRequestUpdate.create({
      supportRequestId: supportRequest.id,
      actorId: user.id,
      action: 'Ticket created',
      notes: subject ? `${subject} :: ${message}` : message
    }, { transaction: t });

    // If a default admin was assigned, record an update
    if (defaultAdmin?.id) {
      await SupportRequestUpdate.create({
        supportRequestId: supportRequest.id,
        actorId: defaultAdmin.id,
        action: defaultAdmin.name ? `Assigned to ${defaultAdmin.name}` : 'Assigned to admin team',
        notes: ''
      }, { transaction: t });
    }

    // Create attachment records
    const files = Array.isArray(req.files) ? req.files : [];
    const attachmentRecords = files.map(file => ({
      supportRequestId: supportRequest.id,
      storedName: path.posix.join('support', file.filename),
      originalName: file.originalname,
      mimeType: file.mimetype,
      size: file.size
    }));

    if (attachmentRecords.length) {
      await SupportRequestAttachment.bulkCreate(attachmentRecords, { transaction: t });

      const attachmentNames = attachmentRecords.map(item => item.originalName).join(', ');
      await SupportRequestUpdate.create({
        supportRequestId: supportRequest.id,
        actorId: user.id,
        action: 'Attachments added',
        notes: attachmentNames
      }, { transaction: t });
    }

    await t.commit();

    const result = await reloadWithIncludes(supportRequest.id);
    res.status(201).json(result);
  } catch (err) {
    await t.rollback();
    cleanupUploadedFiles(req.files);
    res.status(500).json({ msg: 'Server error', error: err.message });
  }
});

/* ── GET /my — requester's own tickets ── */
router.get('/my', auth, async (req, res) => {
  try {
    const requests = await SupportRequest.findAll({
      where: { createdBy: req.user.userId },
      include: standardIncludes,
      order: [['createdAt', 'DESC']]
    });
    res.json(requests);
  } catch (err) {
    res.status(500).json({ msg: 'Server error', error: err.message });
  }
});

/* ── GET / — admin list ── */
router.get('/', auth, requireRole('Super Admin', 'Admin'), async (req, res) => {
  try {
    const status = (req.query.status || '').toString().trim();
    const assigned = (req.query.assigned || '').toString().trim();
    const where = {};
    if (status) {
      where.status = status;
    }
    if (assigned === 'me') {
      where.assignedTo = req.user.userId;
    } else if (assigned) {
      where.assignedTo = assigned;
    }

    const requests = await SupportRequest.findAll({
      where,
      include: standardIncludes,
      order: [['createdAt', 'DESC']],
      limit: 200
    });
    res.json(requests);
  } catch (err) {
    res.status(500).json({ msg: 'Server error', error: err.message });
  }
});

/* ── PATCH /:id — admin update ── */
router.patch('/:id', auth, requireRole('Super Admin', 'Admin'), async (req, res) => {
  const t = await sequelize.transaction();
  try {
    const { status, resolutionNotes, assignedTo, priority } = req.body;
    const supportRequest = await SupportRequest.findByPk(req.params.id, { transaction: t });
    if (!supportRequest) {
      await t.rollback();
      return res.status(404).json({ msg: 'Support request not found' });
    }

    const pendingUpdates = [];

    if (status && status !== supportRequest.status) {
      supportRequest.status = status;
      pendingUpdates.push({ action: `Status changed to ${status}`, notes: '' });
    }
    if (typeof resolutionNotes === 'string' && resolutionNotes !== supportRequest.resolutionNotes) {
      supportRequest.resolutionNotes = resolutionNotes;
      pendingUpdates.push({ action: 'Resolution updated', notes: resolutionNotes });
    }

    if (assignedTo && Number(assignedTo) !== Number(supportRequest.assignedTo)) {
      const newAssigneeDoc = await User.findByPk(assignedTo, { attributes: ['id', 'name', 'email', 'role'] });
      supportRequest.assignedTo = assignedTo;
      const assigneeNote = newAssigneeDoc?.name || newAssigneeDoc?.email || assignedTo;
      pendingUpdates.push({ action: 'Ticket reassigned', notes: `Reassigned to ${assigneeNote}` });
    }

    if (priority && priority !== supportRequest.priority) {
      if (!PRIORITY_VALUES.includes(priority)) {
        await t.rollback();
        return res.status(400).json({ msg: 'Invalid priority supplied.' });
      }
      supportRequest.priority = priority;
      pendingUpdates.push({ action: `Priority set to ${priority}`, notes: '' });
    }

    // Create SupportRequestUpdate records for each change
    for (const update of pendingUpdates) {
      await SupportRequestUpdate.create({
        supportRequestId: supportRequest.id,
        actorId: req.user.userId,
        action: update.action,
        notes: update.notes
      }, { transaction: t });
    }

    await supportRequest.save({ transaction: t });
    await t.commit();

    const result = await reloadWithIncludes(supportRequest.id);
    res.json(result);
  } catch (err) {
    await t.rollback();
    res.status(500).json({ msg: 'Server error', error: err.message });
  }
});

/* ── POST /:id/comment — add comment ── */
router.post('/:id/comment', auth, async (req, res) => {
  try {
    const { note } = req.body;
    if (!note || !note.trim()) {
      return res.status(400).json({ msg: 'Note is required.' });
    }
    const supportRequest = await SupportRequest.findByPk(req.params.id);
    if (!supportRequest) {
      return res.status(404).json({ msg: 'Support request not found' });
    }

    const isOwner = Number(supportRequest.createdBy) === Number(req.user.userId);
    let requesterRole = req.user.role;
    if (!requesterRole) {
      const roleLookup = await User.findByPk(req.user.userId, { attributes: ['role'] });
      requesterRole = roleLookup?.role;
    }
    const isAdmin = ['Super Admin', 'Admin'].includes(requesterRole || '');
    const isAssigned = supportRequest.assignedTo && Number(supportRequest.assignedTo) === Number(req.user.userId);
    if (!isOwner && !isAdmin && !isAssigned) {
      return res.status(403).json({ msg: 'Forbidden' });
    }

    await SupportRequestUpdate.create({
      supportRequestId: supportRequest.id,
      actorId: req.user.userId,
      action: 'Comment added',
      notes: note.trim()
    });

    const result = await reloadWithIncludes(supportRequest.id);
    res.json(result);
  } catch (err) {
    res.status(500).json({ msg: 'Server error', error: err.message });
  }
});

module.exports = router;
